# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         X11-IdleTime
version:      0.07
version_from: IdleTime.pm
installdirs:  site
requires:
    Inline:                        0.44

build_requires:
    Inline::MakeMaker:                        0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
